ARG DISKOVER_VERSION
FROM artifactory.foxsports.com.au:5002/fsa/diskover-base-ftp:${DISKOVER_VERSION}

EXPOSE 9999/tcp 9998/tcp

ENTRYPOINT ["/bin/bash", "entrypoint-diskover-ftp.sh", "--rootdir", "/diskover/rootdir"]